use  piston::input::keyboard::Key;
use  piston::input::*;

#[derive(PartialEq, Eq, Hash, Debug)]
pub enum Keys{
    Unknown,
    Backspace,
    Tab,
    Return,
    Escape,
    Space,
    Exclaim,
    Quotedbl,
    Hash,
    Dollar,
    Percent,
    Ampersand,
    Quote,
    LeftParen,
    RightParen,
    Asterisk,
    Plus,
    Comma,
    Minus,
    Period,
    Slash,
    D0,
    D1,
    D2,
    D3,
    D4,
    D5,
    D6,
    D7,
    D8,
    D9,
    Colon,
    Semicolon,
    Less,
    Equals,
    Greater,
    Question,
    At,
    LeftBracket,
    Backslash,
    RightBracket,
    Caret,
    Underscore,
    Backquote,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Delete,
    CapsLock,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    PrintScreen,
    ScrollLock,
    Pause,
    Insert,
    Home,
    PageUp,
    End,
    PageDown,
    Right,
    Left,
    Down,
    Up,
    NumLockClear,
    NumPadDivide,
    NumPadMultiply,
    NumPadMinus,
    NumPadPlus,
    NumPadEnter,
    NumPad1,
    NumPad2,
    NumPad3,
    NumPad4,
    NumPad5,
    NumPad6,
    NumPad7,
    NumPad8,
    NumPad9,
    NumPad0,
    NumPadPeriod,
    Application,
    Power,
    NumPadEquals,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Execute,
    Help,
    Menu,
    Select,
    Stop,
    Again,
    Undo,
    Cut,
    Copy,
    Paste,
    Find,
    Mute,
    VolumeUp,
    VolumeDown,
    NumPadComma,
    NumPadEqualsAS400,
    AltErase,
    Sysreq,
    Cancel,
    Clear,
    Prior,
    Return2,
    Separator,
    Out,
    Oper,
    ClearAgain,
    CrSel,
    ExSel,
    NumPad00,
    NumPad000,
    ThousandsSeparator,
    DecimalSeparator,
    CurrencyUnit,
    CurrencySubUnit,
    NumPadLeftParen,
    NumPadRightParen,
    NumPadLeftBrace,
    NumPadRightBrace,
    NumPadTab,
    NumPadBackspace,
    NumPadA,
    NumPadB,
    NumPadC,
    NumPadD,
    NumPadE,
    NumPadF,
    NumPadXor,
    NumPadPower,
    NumPadPercent,
    NumPadLess,
    NumPadGreater,
    NumPadAmpersand,
    NumPadDblAmpersand,
    NumPadVerticalBar,
    NumPadDblVerticalBar,
    NumPadColon,
    NumPadHash,
    NumPadSpace,
    NumPadAt,
    NumPadExclam,
    NumPadMemStore,
    NumPadMemRecall,
    NumPadMemClear,
    NumPadMemAdd,
    NumPadMemSubtract,
    NumPadMemMultiply,
    NumPadMemDivide,
    NumPadPlusMinus,
    NumPadClear,
    NumPadClearEntry,
    NumPadBinary,
    NumPadOctal,
    NumPadDecimal,
    NumPadHexadecimal,
    LCtrl,
    LShift,
    LAlt,
    LGui,
    RCtrl,
    RShift,
    RAlt,
    RGui,
    Mode,
    AudioNext,
    AudioPrev,
    AudioStop,
    AudioPlay,
    AudioMute,
    MediaSelect,
    Www,
    Mail,
    Calculator,
    Computer,
    AcSearch,
    AcHome,
    AcBack,
    AcForward,
    AcStop,
    AcRefresh,
    AcBookmarks,
    BrightnessDown,
    BrightnessUp,
    DisplaySwitch,
    KbdIllumToggle,
    KbdIllumDown,
    KbdIllumUp,
    Eject,
    Sleep,
}


pub fn convert_key(k: &Button) -> Option<Keys>{
    match *k{
        Button::Keyboard(Key::Unknown) => Some(Keys::Unknown),
        Button::Keyboard(Key::Backspace) => Some(Keys::Backspace),
        Button::Keyboard(Key::Tab) => Some(Keys::Tab),
        Button::Keyboard(Key::Return) => Some(Keys::Return),
        Button::Keyboard(Key::Escape) => Some(Keys::Escape),
        Button::Keyboard(Key::Space) => Some(Keys::Space),
        Button::Keyboard(Key::Exclaim) => Some(Keys::Exclaim),
        Button::Keyboard(Key::Quotedbl) => Some(Keys::Quotedbl),
        Button::Keyboard(Key::Hash) => Some(Keys::Hash),
        Button::Keyboard(Key::Dollar) => Some(Keys::Dollar),
        Button::Keyboard(Key::Percent) => Some(Keys::Percent),
        Button::Keyboard(Key::Ampersand) => Some(Keys::Ampersand),
        Button::Keyboard(Key::Quote) => Some(Keys::Quote),
        Button::Keyboard(Key::LeftParen) => Some(Keys::LeftParen),
        Button::Keyboard(Key::RightParen) => Some(Keys::RightParen),
        Button::Keyboard(Key::Asterisk) => Some(Keys::Asterisk),
        Button::Keyboard(Key::Plus) => Some(Keys::Plus),
        Button::Keyboard(Key::Comma) => Some(Keys::Comma),
        Button::Keyboard(Key::Minus) => Some(Keys::Minus),
        Button::Keyboard(Key::Period) => Some(Keys::Period),
        Button::Keyboard(Key::Slash) => Some(Keys::Slash),
        Button::Keyboard(Key::D0) => Some(Keys::D0),
        Button::Keyboard(Key::D1) => Some(Keys::D1),
        Button::Keyboard(Key::D2) => Some(Keys::D2),
        Button::Keyboard(Key::D3) => Some(Keys::D3),
        Button::Keyboard(Key::D4) => Some(Keys::D4),
        Button::Keyboard(Key::D5) => Some(Keys::D5),
        Button::Keyboard(Key::D6) => Some(Keys::D6),
        Button::Keyboard(Key::D7) => Some(Keys::D7),
        Button::Keyboard(Key::D8) => Some(Keys::D8),
        Button::Keyboard(Key::D9) => Some(Keys::D9),
        Button::Keyboard(Key::Colon) => Some(Keys::Colon),
        Button::Keyboard(Key::Semicolon) => Some(Keys::Semicolon),
        Button::Keyboard(Key::Less) => Some(Keys::Less),
        Button::Keyboard(Key::Equals) => Some(Keys::Equals),
        Button::Keyboard(Key::Greater) => Some(Keys::Greater),
        Button::Keyboard(Key::Question) => Some(Keys::Question),
        Button::Keyboard(Key::At) => Some(Keys::At),
        Button::Keyboard(Key::LeftBracket) => Some(Keys::LeftBracket),
        Button::Keyboard(Key::Backslash) => Some(Keys::Backslash),
        Button::Keyboard(Key::RightBracket) => Some(Keys::RightBracket),
        Button::Keyboard(Key::Caret) => Some(Keys::Caret),
        Button::Keyboard(Key::Underscore) => Some(Keys::Underscore),
        Button::Keyboard(Key::Backquote) => Some(Keys::Backquote),
        Button::Keyboard(Key::A) => Some(Keys::A),
        Button::Keyboard(Key::B) => Some(Keys::B),
        Button::Keyboard(Key::C) => Some(Keys::C),
        Button::Keyboard(Key::D) => Some(Keys::D),
        Button::Keyboard(Key::E) => Some(Keys::E),
        Button::Keyboard(Key::F) => Some(Keys::F),
        Button::Keyboard(Key::G) => Some(Keys::G),
        Button::Keyboard(Key::H) => Some(Keys::H),
        Button::Keyboard(Key::I) => Some(Keys::I),
        Button::Keyboard(Key::J) => Some(Keys::J),
        Button::Keyboard(Key::K) => Some(Keys::K),
        Button::Keyboard(Key::L) => Some(Keys::L),
        Button::Keyboard(Key::M) => Some(Keys::M),
        Button::Keyboard(Key::N) => Some(Keys::N),
        Button::Keyboard(Key::O) => Some(Keys::O),
        Button::Keyboard(Key::P) => Some(Keys::P),
        Button::Keyboard(Key::Q) => Some(Keys::Q),
        Button::Keyboard(Key::R) => Some(Keys::R),
        Button::Keyboard(Key::S) => Some(Keys::S),
        Button::Keyboard(Key::T) => Some(Keys::T),
        Button::Keyboard(Key::U) => Some(Keys::U),
        Button::Keyboard(Key::V) => Some(Keys::V),
        Button::Keyboard(Key::W) => Some(Keys::W),
        Button::Keyboard(Key::X) => Some(Keys::X),
        Button::Keyboard(Key::Y) => Some(Keys::Y),
        Button::Keyboard(Key::Z) => Some(Keys::Z),
        Button::Keyboard(Key::Delete) => Some(Keys::Delete),
        Button::Keyboard(Key::CapsLock) => Some(Keys::CapsLock),
        Button::Keyboard(Key::F1) => Some(Keys::F1),
        Button::Keyboard(Key::F2) => Some(Keys::F2),
        Button::Keyboard(Key::F3) => Some(Keys::F3),
        Button::Keyboard(Key::F4) => Some(Keys::F4),
        Button::Keyboard(Key::F5) => Some(Keys::F5),
        Button::Keyboard(Key::F6) => Some(Keys::F6),
        Button::Keyboard(Key::F7) => Some(Keys::F7),
        Button::Keyboard(Key::F8) => Some(Keys::F8),
        Button::Keyboard(Key::F9) => Some(Keys::F9),
        Button::Keyboard(Key::F10) => Some(Keys::F10),
        Button::Keyboard(Key::F11) => Some(Keys::F11),
        Button::Keyboard(Key::F12) => Some(Keys::F12),
        Button::Keyboard(Key::PrintScreen) => Some(Keys::PrintScreen),
        Button::Keyboard(Key::ScrollLock) => Some(Keys::ScrollLock),
        Button::Keyboard(Key::Pause) => Some(Keys::Pause),
        Button::Keyboard(Key::Insert) => Some(Keys::Insert),
        Button::Keyboard(Key::Home) => Some(Keys::Home),
        Button::Keyboard(Key::PageUp) => Some(Keys::PageUp),
        Button::Keyboard(Key::End) => Some(Keys::End),
        Button::Keyboard(Key::PageDown) => Some(Keys::PageDown),
        Button::Keyboard(Key::Right) => Some(Keys::Right),
        Button::Keyboard(Key::Left) => Some(Keys::Left),
        Button::Keyboard(Key::Down) => Some(Keys::Down),
        Button::Keyboard(Key::Up) => Some(Keys::Up),
        Button::Keyboard(Key::NumLockClear) => Some(Keys::NumLockClear),
        Button::Keyboard(Key::NumPadDivide) => Some(Keys::NumPadDivide),
        Button::Keyboard(Key::NumPadMultiply) => Some(Keys::NumPadMultiply),
        Button::Keyboard(Key::NumPadMinus) => Some(Keys::NumPadMinus),
        Button::Keyboard(Key::NumPadPlus) => Some(Keys::NumPadPlus),
        Button::Keyboard(Key::NumPadEnter) => Some(Keys::NumPadEnter),
        Button::Keyboard(Key::NumPad1) => Some(Keys::NumPad1),
        Button::Keyboard(Key::NumPad2) => Some(Keys::NumPad2),
        Button::Keyboard(Key::NumPad3) => Some(Keys::NumPad3),
        Button::Keyboard(Key::NumPad4) => Some(Keys::NumPad4),
        Button::Keyboard(Key::NumPad5) => Some(Keys::NumPad5),
        Button::Keyboard(Key::NumPad6) => Some(Keys::NumPad6),
        Button::Keyboard(Key::NumPad7) => Some(Keys::NumPad7),
        Button::Keyboard(Key::NumPad8) => Some(Keys::NumPad8),
        Button::Keyboard(Key::NumPad9) => Some(Keys::NumPad9),
        Button::Keyboard(Key::NumPad0) => Some(Keys::NumPad0),
        Button::Keyboard(Key::NumPadPeriod) => Some(Keys::NumPadPeriod),
        Button::Keyboard(Key::Application) => Some(Keys::Application),
        Button::Keyboard(Key::Power) => Some(Keys::Power),
        Button::Keyboard(Key::NumPadEquals) => Some(Keys::NumPadEquals),
        Button::Keyboard(Key::F13) => Some(Keys::F13),
        Button::Keyboard(Key::F14) => Some(Keys::F14),
        Button::Keyboard(Key::F15) => Some(Keys::F15),
        Button::Keyboard(Key::F16) => Some(Keys::F16),
        Button::Keyboard(Key::F17) => Some(Keys::F17),
        Button::Keyboard(Key::F18) => Some(Keys::F18),
        Button::Keyboard(Key::F19) => Some(Keys::F19),
        Button::Keyboard(Key::F20) => Some(Keys::F20),
        Button::Keyboard(Key::F21) => Some(Keys::F21),
        Button::Keyboard(Key::F22) => Some(Keys::F22),
        Button::Keyboard(Key::F23) => Some(Keys::F23),
        Button::Keyboard(Key::F24) => Some(Keys::F24),
        Button::Keyboard(Key::Execute) => Some(Keys::Execute),
        Button::Keyboard(Key::Help) => Some(Keys::Help),
        Button::Keyboard(Key::Menu) => Some(Keys::Menu),
        Button::Keyboard(Key::Select) => Some(Keys::Select),
        Button::Keyboard(Key::Stop) => Some(Keys::Stop),
        Button::Keyboard(Key::Again) => Some(Keys::Again),
        Button::Keyboard(Key::Undo) => Some(Keys::Undo),
        Button::Keyboard(Key::Cut) => Some(Keys::Cut),
        Button::Keyboard(Key::Copy) => Some(Keys::Copy),
        Button::Keyboard(Key::Paste) => Some(Keys::Paste),
        Button::Keyboard(Key::Find) => Some(Keys::Find),
        Button::Keyboard(Key::Mute) => Some(Keys::Mute),
        Button::Keyboard(Key::VolumeUp) => Some(Keys::VolumeUp),
        Button::Keyboard(Key::VolumeDown) => Some(Keys::VolumeDown),
        Button::Keyboard(Key::NumPadComma) => Some(Keys::NumPadComma),
        Button::Keyboard(Key::NumPadEqualsAS400) => Some(Keys::NumPadEqualsAS400),
        Button::Keyboard(Key::AltErase) => Some(Keys::AltErase),
        Button::Keyboard(Key::Sysreq) => Some(Keys::Sysreq),
        Button::Keyboard(Key::Cancel) => Some(Keys::Cancel),
        Button::Keyboard(Key::Clear) => Some(Keys::Clear),
        Button::Keyboard(Key::Prior) => Some(Keys::Prior),
        Button::Keyboard(Key::Return2) => Some(Keys::Return2),
        Button::Keyboard(Key::Separator) => Some(Keys::Separator),
        Button::Keyboard(Key::Out) => Some(Keys::Out),
        Button::Keyboard(Key::Oper) => Some(Keys::Oper),
        Button::Keyboard(Key::ClearAgain) => Some(Keys::ClearAgain),
        Button::Keyboard(Key::CrSel) => Some(Keys::CrSel),
        Button::Keyboard(Key::ExSel) => Some(Keys::ExSel),
        Button::Keyboard(Key::NumPad00) => Some(Keys::NumPad00),
        Button::Keyboard(Key::NumPad000) => Some(Keys::NumPad000),
        Button::Keyboard(Key::ThousandsSeparator) => Some(Keys::ThousandsSeparator),
        Button::Keyboard(Key::DecimalSeparator) => Some(Keys::DecimalSeparator),
        Button::Keyboard(Key::CurrencyUnit) => Some(Keys::CurrencyUnit),
        Button::Keyboard(Key::CurrencySubUnit) => Some(Keys::CurrencySubUnit),
        Button::Keyboard(Key::NumPadLeftParen) => Some(Keys::NumPadLeftParen),
        Button::Keyboard(Key::NumPadRightParen) => Some(Keys::NumPadRightParen),
        Button::Keyboard(Key::NumPadLeftBrace) => Some(Keys::NumPadLeftBrace),
        Button::Keyboard(Key::NumPadRightBrace) => Some(Keys::NumPadRightBrace),
        Button::Keyboard(Key::NumPadTab) => Some(Keys::NumPadTab),
        Button::Keyboard(Key::NumPadBackspace) => Some(Keys::NumPadBackspace),
        Button::Keyboard(Key::NumPadA) => Some(Keys::NumPadA),
        Button::Keyboard(Key::NumPadB) => Some(Keys::NumPadB),
        Button::Keyboard(Key::NumPadC) => Some(Keys::NumPadC),
        Button::Keyboard(Key::NumPadD) => Some(Keys::NumPadD),
        Button::Keyboard(Key::NumPadE) => Some(Keys::NumPadE),
        Button::Keyboard(Key::NumPadF) => Some(Keys::NumPadF),
        Button::Keyboard(Key::NumPadXor) => Some(Keys::NumPadXor),
        Button::Keyboard(Key::NumPadPower) => Some(Keys::NumPadPower),
        Button::Keyboard(Key::NumPadPercent) => Some(Keys::NumPadPercent),
        Button::Keyboard(Key::NumPadLess) => Some(Keys::NumPadLess),
        Button::Keyboard(Key::NumPadGreater) => Some(Keys::NumPadGreater),
        Button::Keyboard(Key::NumPadAmpersand) => Some(Keys::NumPadAmpersand),
        Button::Keyboard(Key::NumPadDblAmpersand) => Some(Keys::NumPadDblAmpersand),
        Button::Keyboard(Key::NumPadVerticalBar) => Some(Keys::NumPadVerticalBar),
        Button::Keyboard(Key::NumPadDblVerticalBar) => Some(Keys::NumPadDblVerticalBar),
        Button::Keyboard(Key::NumPadColon) => Some(Keys::NumPadColon),
        Button::Keyboard(Key::NumPadHash) => Some(Keys::NumPadHash),
        Button::Keyboard(Key::NumPadSpace) => Some(Keys::NumPadSpace),
        Button::Keyboard(Key::NumPadAt) => Some(Keys::NumPadAt),
        Button::Keyboard(Key::NumPadExclam) => Some(Keys::NumPadExclam),
        Button::Keyboard(Key::NumPadMemStore) => Some(Keys::NumPadMemStore),
        Button::Keyboard(Key::NumPadMemRecall) => Some(Keys::NumPadMemRecall),
        Button::Keyboard(Key::NumPadMemClear) => Some(Keys::NumPadMemClear),
        Button::Keyboard(Key::NumPadMemAdd) => Some(Keys::NumPadMemAdd),
        Button::Keyboard(Key::NumPadMemSubtract) => Some(Keys::NumPadMemSubtract),
        Button::Keyboard(Key::NumPadMemMultiply) => Some(Keys::NumPadMemMultiply),
        Button::Keyboard(Key::NumPadMemDivide) => Some(Keys::NumPadMemDivide),
        Button::Keyboard(Key::NumPadPlusMinus) => Some(Keys::NumPadPlusMinus),
        Button::Keyboard(Key::NumPadClear) => Some(Keys::NumPadClear),
        Button::Keyboard(Key::NumPadClearEntry) => Some(Keys::NumPadClearEntry),
        Button::Keyboard(Key::NumPadBinary) => Some(Keys::NumPadBinary),
        Button::Keyboard(Key::NumPadOctal) => Some(Keys::NumPadOctal),
        Button::Keyboard(Key::NumPadDecimal) => Some(Keys::NumPadDecimal),
        Button::Keyboard(Key::NumPadHexadecimal) => Some(Keys::NumPadHexadecimal),
        Button::Keyboard(Key::LCtrl) => Some(Keys::LCtrl),
        Button::Keyboard(Key::LShift) => Some(Keys::LShift),
        Button::Keyboard(Key::LAlt) => Some(Keys::LAlt),
        Button::Keyboard(Key::LGui) => Some(Keys::LGui),
        Button::Keyboard(Key::RCtrl) => Some(Keys::RCtrl),
        Button::Keyboard(Key::RShift) => Some(Keys::RShift),
        Button::Keyboard(Key::RAlt) => Some(Keys::RAlt),
        Button::Keyboard(Key::RGui) => Some(Keys::RGui),
        Button::Keyboard(Key::Mode) => Some(Keys::Mode),
        Button::Keyboard(Key::AudioNext) => Some(Keys::AudioNext),
        Button::Keyboard(Key::AudioPrev) => Some(Keys::AudioPrev),
        Button::Keyboard(Key::AudioStop) => Some(Keys::AudioStop),
        Button::Keyboard(Key::AudioPlay) => Some(Keys::AudioPlay),
        Button::Keyboard(Key::AudioMute) => Some(Keys::AudioMute),
        Button::Keyboard(Key::MediaSelect) => Some(Keys::MediaSelect),
        Button::Keyboard(Key::Www) => Some(Keys::Www),
        Button::Keyboard(Key::Mail) => Some(Keys::Mail),
        Button::Keyboard(Key::Calculator) => Some(Keys::Calculator),
        Button::Keyboard(Key::Computer) => Some(Keys::Computer),
        Button::Keyboard(Key::AcSearch) => Some(Keys::AcSearch),
        Button::Keyboard(Key::AcHome) => Some(Keys::AcHome),
        Button::Keyboard(Key::AcBack) => Some(Keys::AcBack),
        Button::Keyboard(Key::AcForward) => Some(Keys::AcForward),
        Button::Keyboard(Key::AcStop) => Some(Keys::AcStop),
        Button::Keyboard(Key::AcRefresh) => Some(Keys::AcRefresh),
        Button::Keyboard(Key::AcBookmarks) => Some(Keys::AcBookmarks),
        Button::Keyboard(Key::BrightnessDown) => Some(Keys::BrightnessDown),
        Button::Keyboard(Key::BrightnessUp) => Some(Keys::BrightnessUp),
        Button::Keyboard(Key::DisplaySwitch) => Some(Keys::DisplaySwitch),
        Button::Keyboard(Key::KbdIllumToggle) => Some(Keys::KbdIllumToggle),
        Button::Keyboard(Key::KbdIllumDown) => Some(Keys::KbdIllumDown),
        Button::Keyboard(Key::KbdIllumUp) => Some(Keys::KbdIllumUp),
        Button::Keyboard(Key::Eject) => Some(Keys::Eject),
        Button::Keyboard(Key::Sleep) => Some(Keys::Sleep),
        _ => None
    }
}
